qlcchain/go-qlc

common/types/balance.go, common/types/balance_test.go, consensus/election.go
- use online representation of 50% of total weight as a consensus threshold
- fix #119 
=> feat: use online representation of 50% of total weight as a consensus threshold

config/config_manager_test.go, config/config_v2.go, config/defaults_test.go
=> fix: default rpc public modules is nil

config/config_manager.go, config/config_v1.go, config/config_v2.go, config/migration_v1_v2.go
- fix test net boot nodes
- migration rpc endpoint config to v2
- migration all p2p config to v2
N/A
=> fix: migration rpc/p2p config to v2

cmd/client/commands/root.go, cmd/rpc/main.go, rpc/api/ledger.go, test/mock/mock.go
add timestamp to AccountsPending api
=> feat: add timestamp to AccountsPending api

common/types/balance.go
=> fix: parseInt on 32bit OS

rpc/api/rewards.go, rpc/api/rewards_test.go, vm/contract/abi/abi_rewards.go, vm/contract/abi/abi_rewards_test.go, vm/contract/contract.go, vm/contract/rewards.go
- add test case for rewards contract
-  merge generate confidant/airdrop receive block into one
- [] Bug fix: (Link to the issue #{issue No.})
N/A
=> refactor: simplified rewards contract RPC interface

p2p/sync.go, rpc/api/net.go
=> feat: add sync status rpc interface

cmd/server/commands/root.go
=> fix: configParams bug when use default config name

ledger/ledger.go, rpc/api/ledger.go
- fix `ledger_pendings` interface
- fix `GenerateReceiveBlock` possible NPE
N/A
=> fix: `ledger_pendings` does not return data when error occurs

vm/contract/rewards.go
fix verify exist rewards block data
N/A
=> fix: verify exist data when generate rewards data

Makefile, go.mod
feat: remove build tag sqlite_userauth
=> feat: remove build tag sqlite_userauth

ledger/process/ledger_processor.go, ledger/process/verifier.go, rpc/api/ledger.go
feat: check generate receive block repeatedly
=> feat: check generate receive block repeatedly

p2p/node.go, p2p/stream.go, rpc/api/ledger.go, rpc/api/ledger_test.go
- feat: it is forbidden to send a transaction when there is no node connection.
- refactor ping service.
- fix #667 
=> fix: don't process transaction when node offline

common/types/account.go, common/types/account_test.go, ledger/ledger_account_cache.go, ledger/ledger_account_test.go
- token pointer in ledger cache cause account info error
=> fix: token pointer in ledger cache cause account info error

rpc/api/ledger.go, rpc/api/pov.go
pubsub notify data should same with api block.
=> fix: pubsub notify data should same with api block

ledger/ledger_pending.go, rpc/api/ledger.go
- pubsub notify data same with api accountmeta
=> feat: pubsub notify data same with api accountmeta

consensus/pov/consensus_pov.go, consensus/pov/pov_pow.go, consensus/pov/pov_verifier_test.go, miner/pov_worker.go
pov verify producer shoud use current header miner.
=> fix: pov verify producer shoud use current header miner

consensus/pov/pov_txpool.go
change pov txpool max txs limit, from 100k to 1m.
=> fix: change pov txpool max txs limit

consensus/pov/pov_chain.go, consensus/pov/pov_impl.go
pov should use event broadcast, as p2p service is using libp2p pubsub.
=> fix: pov should use event broadcast

consensus/dpos/active_transactions.go, consensus/dpos/dpos_impl.go, ledger/process/rollback.go
delete the block in the unchecked that depends on the current block when the current block consensus times out to fix #749 
=> fix: delete the useless block in the unchecked 

ledger/ledger_vote_history.go, rpc/api/ledger.go
- delete from iterator
- Representatives api not return Representation with ZeroBalance
=> fix: delete from iterator

consensus/dpos/dpos_impl.go
- miner contract blocks need to be synchronized in order
=> fix: miner contract blocks need to be synchronized in order

common/genesis_pov.go, common/genesis_pov_test.go
update pov mainnet genesis to sha256d.
=> fix: update pov mainnet genesis to sha256d

ledger/relation/relation_impl.go
- apply memory once when batch update blocks to sqlite
=> fix: apply memory once when batch update blocks to sqlite

common/genesis.go, ledger/relation/relation_impl.go, rpc/api/ledger.go, rpc/api/mintage.go, rpc/apis.go
- add pov status to mintage api 
- relation module subscribe event bus
- add apis to get genesis blocks
=> fix: add pov status to mintage api 

common/statedb/pov_statedb.go, trie/node_pool.go
optimize pov trie perf using new cache.
=> feat: optimize pov trie perf

rpc/api/settlement.go, vm/contract/settlement.go, vm/contract/settlement_test.go
- merge all generate rewards block API into one
- implement `GetTargetReceiver`
=> fix: generate settlement contract rewards block

vm/contract/abi/abi_settlement.go, vm/contract/abi/abi_settlement_gen.go, vm/contract/abi/abi_settlement_gen_test.go, vm/contract/abi/abi_settlement_test.go
new output result
```json
{
"jsonrpc": "2.0",
"id": 3,
"result": {
"contract": {
"partyA": {
"address": "qlc_3giz1uwgsmq46xzspo9mbutade6foqh5fuja4m9rwfiuyzp4x8zu5hkorq4z",
"name": "PCCWG"
},
"partyB": {
"address": "qlc_3exbms47d63ywggnhb9iko9twphsnsx563qf6faufp33167o5dqfoawa8gtj",
"name": "HKTCSL"
},
"previous": "a77862e3de249df4c95f17df399a902f23e377ae0d05cf2e4becc83247b9591d",
"services": [
{
"serviceId": "ab3d2c3d0be06e7f6bab089e198c7816a1ae88fb241ca94d7a8df09ad95abfd0",
"mcc": 460,
"mnc": 46,
"totalAmount": 10000,
"unitPrice": 0.0426,
"currency": "USD"
},
{
"serviceId": "b5983e8ac72f04548fa99789b08014904f71e1f5b48c5d47fff8507efd51d85a",
"mcc": 460,
"mnc": 2,
"totalAmount": 300000,
"unitPrice": 0.023,
"currency": "USD"
}
],
"signDate": …
```
=> refactor: update summary report data structure

consensus/dpos/dpos_impl_test.go, consensus/dpos/dpos_integration_test.go, consensus/dpos/dpos_test.go, consensus/dpos/online_test.go, consensus/dpos/processor_test.go, vm/contract/abi/abi_permission.go
nodes count exclude the removed nodes
=> fix: nodes count exclude the removed ones

chain/context/chain_context.go, chain/helper.go, chain/permission_service.go, chain/permission_service_test.go, config/config.go, config/config_test.go, config/config_v2.go, config/config_v2_default.go, config/config_v2_testnet.go, config/config_v7.go, config/defaults_net.go, config/defaults_testnet.go, config/genesis_test.go, config/genesis_testnet_test.go, config/migration_v5_v6.go, config/migration_v6_v7.go, config/migration_v6_v7_test.go, config/migration_v6_v7_testnet_test.go, ledger/process/ledger_processor.go, ledger/process/ledger_processor_test.go, p2p/node.go, p2p/protector_test.go, p2p/qlcService.go, rpc/api/ledger.go
- add permission service to add preconfigured nodes automatically
- add preconfigured nodes in config file
=> feat: add permission service to add preconfigured nodes automatically

rpc/api/net.go, rpc/api/net_test.go
=> feat: add an rpc interface to query the peerid of node

p2p/node.go
=> fix: when getting onlineinfo, own ip is incorrect

ledger/ledger.go, ledger/process/ledger_processor.go
- delete the cache block instantly can cause high disk usage
=> hotfix: delete the cache block instantly can cause high disk usage

go.mod, go.sum
=> chore(deps): bump github.com/awnumar/memguard from 0.16.2 to 0.22.2

common/storage/storage.go, ledger/ledger.go, ledger/ledger_pending.go, ledger/migration/migration.go, ledger/migration/migration_test.go, rpc/api/ledger_test.go, rpc/grpc/apis/ledger_test.go
migration ledger to reset pendings, fix bug:
```
"pendingKey deserialize: invalid Hash size"
```
=> fix: upgrade ledger to reset pending infos

cmd/client/commands/kyc_admin_update.go, cmd/client/commands/kyc_operator_update.go, cmd/client/commands/kyc_status_update.go, cmd/client/commands/kyc_trade_address_update.go, consensus/dpos/dpos_impl_testnet_test.go, ledger/migration/migration.go, p2p/node_test.go, rpc/api/kyc.go, rpc/api/kyc_test.go, rpc/api/ledger_default_test.go, rpc/api/ledger_testnet_test.go, rpc/api/pov_pubsub.go, vm/contract/abi/abi_kyc.go, vm/contract/abi/abi_kyc_test.go, vm/contract/abi/abi_kyc_types.go, vm/contract/kyc.go, vm/contract/kyc_test.go, vm/contract/nep5_pledge.go, vm/contract/nep5_pledge_test.go
- remove nep5 contract pending data
- fix pov pub/sub
=> fix: remove nep5 contract pending data

config/config_v10.go, config/config_v10_testnet.go, ledger/cache.go, ledger/ledger.go, ledger/ledger_uncheck.go, ledger/ledger_uncheck_test.go, rpc/api/ledger.go, rpc/api/ledger_test.go, rpc/grpc/apis/ledger_test.go
- config to adjust unchecked flush interval
=> feat: config to adjust unchecked flush interval

cmd/server/commands/root.go, ledger/process/ledger_check.go, privacy/client.go, privacy/privacy.go, privacy/ptm.go, rpc/api/dod_settlement.go
=> fix: wrong block into ledger cache && `DoDSettlement_GetPendingResourceCheck` return incorrect order infos

consensus/dpos/dpos_impl_testnet.go, vm/contract/dod_settlement.go
=> fix: node without ptm can not synchronize privacy block

rpc/api/pov.go, rpc/rpc.go
- call pov_getRepStats timeout , fix #1372
=> fix: pov_getRepStats timeout
