qlcchain/go-qlc

cmd/network/main.go
ledger/db/badger_impl.go
ledger/db/badger_impl_test.go
ledger/db/dbstore.go
ledger/db/migration.go
ledger/db/migration_test.go
ledger/ledger.go
ledger/ledger_test.go
ledger/ledgerstore.go
sync/sync.go
wallet/wallet.go
wallet/wallet_test.go
wallet/walletapi.go
wallet/walletapi_impl.go

- add migration interface
- implement ledger as singleton
- refine ledger store
- refine db store interface and implement

refine ledger interface and implement 

---

crypto/crypto.go
crypto/crypto_test.go
go.mod
ledger/ledgerstore.go
wallet/wallet.go
wallet/wallet_encrypt.go
wallet/wallet_manager.go
wallet/wallet_manager_test.go
wallet/walletapi.go
wallet/walletapi_impl.go
wallet/walletapi_impl_test.go

- add wallet manager interface
- implement wallet manager interface
- implement password encrypt and decrypt
- refine wallet interface
TODO:
- add test case

[WIP]implement wallet module

---

common/task.go
common/types/account_test.go
common/types/address.go
common/types/address_test.go
common/types/hash.go
common/types/seed_test.go
common/types/unchecked.go
config/defaults.go
crypto/random/random_test.go
ledger/db/badger_impl.go
ledger/ledger.go
wallet/wallet.go
wallet/wallet_impl.go
wallet/wallet_impl_test.go
wallet/wallet_manager_impl.go
wallet/wallet_manager_impl_test.go

[WIP]add more test case

---

ci/travis.codecov.sh
cmd/network/main.go
consensus/block_processor.go
consensus/block_processor_test.go
ledger/db/badger_impl.go
ledger/ledger.go
ledger/ledger_test.go
ledger/ledgerstore.go
p2p/sync.go
wallet/wallet_encrypt_test.go
wallet/wallet_impl.go
wallet/wallet_impl_test.go
wallet/wallet_manager_impl.go
wallet/wallet_manager_impl_test.go
wallet/wallet_test.go

ledger/wallet support concurrent op to speedup test case

speedup test case

---

ledger/ledger.go
ledger/ledger_processor.go
ledger/ledger_processor_test.go
ledger/ledger_test.go
ledger/testdata/blocks_ledger_process.json
ledger/testdata/blocks_rollback.json

implement ledger rollback and block validate process
N/A

feat: implement ledger rollback and block validate process

---

chain/qlc.go
common/mock.go
ledger/ledger_service.go
log/log_service.go
log/logger.go
log/logger_test.go
wallet/wallet.go
wallet/wallet_service.go

Implement internal service for log, ledger and wallet. And add the services ref to the global Context.
N/A

feat: Add log, wallet, ledger internal service

---

cmd/main.go
common/types/block.go

add cli func ,include import seed , add send block , receive block

feat: add cli func

---

p2p/protos/bulkpull.go
p2p/protos/bulkpull_test.go
p2p/protos/bulkpushblock.go
p2p/protos/bulkpushblock_test.go
p2p/protos/confirmack.go
p2p/protos/confirmack_test.go
p2p/protos/confirmreq.go
p2p/protos/confirmreq_test.go
p2p/protos/frontier.go
p2p/protos/frontier_test.go
p2p/protos/publish.go
p2p/protos/publish_test.go

style:format code

---

cmd/main.go

feature: cli add send times optional

---

cmd/main.go

fix: cli auto get root_token type

---

Makefile

add LDFLAGS for cross build
- N/A Read the [CONTRIBUTION](https://github.com/qlcchain/go-qlc/blob/master/CONTRIBUTING.md).
- N/A All the tests are passing after the introduction of new changes.
- N/A Added tests respective to the part of code I have written.
- N/A Added proper documentation where ever applicable.
- N/A Code has been written according to [Golang-Style-Guide](https://github.com/qlcchain/go-qlc/blob/master/CONTRIBUTING.md#code-standard)

chore: add LDFLAGS

---

common/types/abi_test.go
common/types/address_test.go
common/types/block_test.go
common/types/hash_test.go
common/types/work_test.go
config/config_manager.go

replace jsoniter with std json
N/A

refactor: replace jsoniter with std json

---

config/defaults.go

chore: change p2p and rpc port

---

config/defaults.go
consensus/dpos_impl.go
rpc/api/qlcapi.go
rpc/rpc_test.go

fix rpc api func process() 
N/A

fix: rpcapi-process()

---

test/mock/mock.go

fix: mock stateblock

---

rpc/api/qlcapi.go

fix: amountbalance NPE

---

rpc/api/qlcapi.go

fix AccountHistoryTopn() returns one more block
N/A

fix: AccountHistoryTopn() returns one more block

---

consensus/active_transactions.go
consensus/block_processor.go
consensus/dpos_impl.go
p2p/sync.go

fix: let node know online representatives

---

config/defaults.go
rpc/api/qlcapi.go
rpc/rpc_test.go

- refactor: rpcapi AccountHistoryTopn func
- fix: windows ipc testcase
N/A

refactor: rpcapi-AccountHistoryTopn()

---

cmd/commands/block_count.go
cmd/commands/root.go
cmd/commands/send.go
cmd/commands/version.go
cmd/commands/wallet_change_password.go
cmd/commands/wallet_create.go
cmd/commands/wallet_import.go
cmd/commands/wallet_list.go
cmd/commands/wallet_remove.go
config/config_manager.go
config/config_manager_test.go
config/config_test.go
config/defaults.go
ledger/ledger_service_test.go
log/logger_test.go
wallet/wallet_impl_test.go
wallet/wallet_manager_impl_test.go
wallet/wallet_service_test.go

fix: support choose config path

---

config/defaults.go
rpc/rpc_test.go

fix: windows ipc endpoint

---

ledger/ledger.go

fix: solve synchronization problems caused by frontier incorrect sorting

---

rpc/json.go
rpc/rpc.go

print debug info to rpc request
N/A

feature: print debug info to rpc request

---

.travis.yml

chore: build all platforms binary

---

consensus/active_transactions.go
consensus/dpos_impl.go
p2p/dispatcher.go
p2p/messageMonitor.go
p2p/streamManager.go
p2p/sync.go

- optimize code that processes large amounts of data.

fix: cpu too high.

---

consensus/dpos_impl.go

chore: make online Representatives easier to find

---

consensus/active_transactions.go
consensus/dpos_impl.go

fix: change map to sync.map for roots

---

cmd/commands/account.go
cmd/commands/batch_send.go
cmd/commands/utils.go
common/types/account.go

- generate account by seed
- send token to multi accounts
N/A

feat: add create account and batch send token commands

---

cmd/commands/account.go
common/types/account.go
common/types/account_test.go
common/types/performance_time.go
common/types/performance_time_test.go
ledger/ledger.go
ledger/ledger_test.go
ledger/ledgerstore.go

- implement save/load performance test time
- optimize account string and add test case
N/A

feat: implement save/load performance test time

---

cmd/commands/block_create.go
cmd/commands/utils.go
ledger/ledger_processor.go
ledger/ledger_test.go

add cli command to batch create block
N/A

feature: add cli command blocks create

---

cmd/commands/block_create.go
cmd/commands/utils.go
cmd/rpc/main.go
common/types/account.go
ledger/ledger.go
ledger/ledger_processor.go
ledger/ledger_test.go
ledger/ledgerstore.go
rpc/api/account.go
rpc/api/ledger.go
rpc/api/qlcapi.go
rpc/apis.go
rpc/rpc_test.go
test/mock/mock.go

add ledger interface in json-rpc
N/A

feat:add ledger interface in json-rpc

---

cmd/commands/batch_send.go
cmd/commands/send.go
cmd/commands/token_list.go
cmd/commands/utils.go
common/types/account.go
common/types/account_test.go
common/types/signature_test.go
common/util/util.go
config/config_manager.go
config/config_manager_test.go
config/defaults.go
consensus/dpos_impl.go
consensus/utils_test.go
consensus/votes_test.go
go.mod
ledger/ledger_service.go
log/logger.go
log/logger_test.go
p2p/protos/bulkpull_test.go
p2p/protos/bulkpushblock_test.go
p2p/protos/confirmack_test.go
p2p/protos/confirmreq_test.go
p2p/protos/publish_test.go
rpc/api/ledger.go
rpc/rpc_service.go
test/mock/mock.go
test/mock/mock_test.go
wallet/wallet_encrypt.go
wallet/wallet_manager_impl.go
wallet/wallet_manager_impl_test.go

- use std json lib
- send tx by RPC api
N/A

feat: use std json

---

cmd/commands/block_create.go
cmd/rpc/main.go
ledger/ledger_processor.go
rpc/api/account.go
rpc/api/account_test.go
rpc/api/ledger.go
rpc/apis.go

add account interface to json-rpc
N/A

feat:add account interface to json-rpc

---

cmd/rpc/main.go
common/util/encrypt.go
common/util/encrypt_test.go
rpc/api/account.go
rpc/api/ledger.go
rpc/api/net.go
rpc/api/util.go
rpc/api/wallet.go
rpc/apis.go
rpc/rpc.go
wallet/wallet_impl.go

add wallet,util and net interface to json-rpc .
N/A

feat: add wallet,util and net interface to json-rpc

---

ledger/ledger.go
ledger/ledger_processor_test.go
ledger/ledger_test.go
ledger/ledgerstore.go
rpc/api/ledger.go
rpc/rpc_test.go
rpc/server.go

- modify the way to get all data in a badger table
- modify rpc test case
N/A

refactor: modify the way to get all data in a badger table

---

consensus/block_processor.go

fix: bug for get uncheckedblock from db(#122)

---

consensus/active_transactions.go
consensus/dpos_impl.go
consensus/election.go
p2p/messageMonitor.go
p2p/messageMonitor_test.go
p2p/node.go
p2p/qlcService.go
p2p/streamManager.go
p2p/sync.go
p2p/types.go
rpc/api/ledger.go

feat: optimization of the external interface of p2p messages(#125)

---

cmd/rpc/main.go
common/types/unchecked.go
consensus/block_processor.go
ledger/ledger.go
ledger/ledger_test.go
ledger/ledgerstore.go

add meta data for uncheckedblock table  to fix #133 
N/A

feat: add meta data for uncheckedblock table from db

---

cmd/client/commands/account.go
cmd/client/commands/balance.go
cmd/client/commands/batch_send.go
cmd/client/commands/block_count.go
cmd/client/commands/endpoint.go
cmd/client/commands/performance.go
cmd/client/commands/root.go
cmd/client/commands/send.go
cmd/client/commands/tokens.go
cmd/client/commands/util.go
cmd/client/commands/version.go
cmd/client/commands/wallet_change_password.go
cmd/client/commands/wallet_create.go
cmd/client/commands/wallet_list.go
cmd/client/commands/wallet_remove.go
cmd/server/commands/root.go
cmd/server/commands/wallet_import.go
go.mod
rpc/client.go

implement interactive cli by ishell library, fix #126 
N/A

feat: implement interactive cli by ishell library

---

cmd/client/commands/root.go
cmd/client/commands/send.go
cmd/client/commands/wallet_create.go
config/config_manager_test.go
rpc/api/ledger.go
rpc/rpc_service.go
rpc/rpc_test.go

set balance unit to raw in rpc parameter and return

feat: set balance unit to raw in rpc parameter and return

---

cmd/rpc/main.go
ledger/db/badger_impl.go
ledger/ledger.go
ledger/ledger_migration.go
ledger/ledger_processor.go
ledger/ledger_processor_test.go
ledger/ledger_service.go
ledger/ledger_test.go
ledger/ledgerstore.go
p2p/sync.go
rpc/api/qlcapi.go
rpc/rpc_test.go

- add a table for storage blocks relationship to fix #135 
- add version for ledger

feat: add table for blocks relationship

---

.travis.yml
go.mod
ledger/db/badger_impl.go

fix libp2p caused travis ci build fail
- N/A Added tests respective to the part of code I have written.
- N/A Added proper documentation where ever applicable.
N/A

fix libp2p dependence

---

common/types/balance.go
common/types/balance_test.go
common/types/hash.go
common/types/hash_test.go
common/util/math_big.go
common/util/math_integer.go
common/util/math_test.go
common/util/util.go
go.mod
rpc/api/qlcapi.go
vm/compiler/module.go

- fix balance safe add/sub overflow
- fix rpc api typo
- add `BytesToHash()`
- use qlc forked wagon instead of perlin's
N/A

feat: optimize common lib

---

ledger/ledger.go
ledger/ledger_processor.go
ledger/ledger_service.go
ledger/ledger_service_test.go
wallet/wallet_service_test.go

- execute blockprocess in a transaction

fix: execute blockprocess in a transaction

---

.travis.yml
ci/travis.codecov.sh
go.mod
go.sum
ledger/db/badger_impl.go
wallet/wallet_impl.go
wallet/wallet_impl_test.go
wallet/wallet_manager_impl_test.go

- enable VM test cases
- upgrade trusty to xenial

chore: enhance CI

---

p2p/discovery.go
p2p/messageMonitor.go
p2p/node.go
p2p/qlcService.go
p2p/streamManager.go

fix: mdns bug and node discovery structure adjustment.

---

consensus/active_transactions.go
consensus/dpos_impl.go

fix: consensus module init account bug.

---

common/types/performance_time.go
config/config.go
config/config_manager_test.go
config/defaults.go
consensus/active_transactions.go
consensus/dpos_impl.go
consensus/election.go
p2p/messageMonitor.go
p2p/sync.go

feat: merge performance test code and add configuration switches for performance 

---

ledger/ledger_storage.go
rpc/api/contract.go
vm/abi/contract/abi_mintage.go
vm/contract/mintage.go

fix: ledger unpack TokenInfo

---

p2p/node.go

fix: peer ID conversion bug.

---

common/types/block_state.go
common/util/bytes.go
ledger/ledger.go
ledger/ledger_storage.go
ledger/ledger_storage_test.go
ledger/ledgerstore.go
vm/contract/mintage.go

implement ledger interface to store contract data #173 

feat: implement ledger interface to store contract data

---

config/config.go
config/defaults.go
p2p/discovery.go
p2p/node.go
p2p/streamManager.go
p2p/sync.go

feat: add p2p parameters to the configuration file

---

cmd/rpc/main.go
ledger/ledger.go
ledger/ledger_migration.go
ledger/ledger_storage.go
ledger/ledger_storage_test.go
ledger/ledger_test.go
ledger/ledgerstore.go
rpc/api/ledger.go

add interface to get block by phone number, #145 

 feat: add interface to get block by phone number

---

p2p/messageMonitor.go
p2p/streamManager.go

fix: message cache bug in p2p module

---

consensus/active_transactions.go
consensus/block_processor.go
consensus/dpos_impl.go
consensus/election.go
consensus/votes.go
p2p/dispatcher.go
p2p/messageMonitor.go
p2p/node.go
p2p/stream.go
p2p/streamManager.go
p2p/sync.go

- fix bugs found in performance test.

chore: optimize performance for p2p and consensus.

---

consensus/dpos_impl_test.go
consensus/election.go
p2p/discovery_test.go
p2p/messageMonitor.go
p2p/messageMonitor_test.go
p2p/message_test.go
p2p/node_test.go
p2p/streamManager_test.go

- add p2p and consensus testcase
- closes #146 ,closes #147 

feat：add p2p and consensus testcase

---

consensus/active_transactions.go
consensus/dpos_impl.go

fix: find online representatives bug

---

ledger/ledger_contract_test.go
ledger/ledger_sms_test.go
ledger/ledger_test.go
rpc/api/ledger.go
rpc/api/mintage.go
test/mock/mock.go

feat: add ledger testcase

---

consensus/active_transactions.go
consensus/dpos_impl.go
consensus/election.go

fix: online Representatives bug

---

cmd/rpc/main.go
ledger/ledger.go
ledger/ledger_test.go
ledger/ledgerstore.go
rpc/api/ledger.go
rpc/api/sms.go
test/mock/mock_test.go

- refactor  accountsPending rpc interface
- rpc cmd 

refactor: accountsPending rpc interface

---

cmd/server/commands/utils.go
config/config.go
config/defaults.go

feat: add switch that automatically generates receive block

---

rpc/api/ledger.go
rpc/api/mintage.go

move tokeninfo interface from mintage to ledger

feat: move tokeninfo interface from mintage to ledger

---

consensus/election.go

chore: Optimize the code for calculating weights

---

cmd/server/commands/root.go
cmd/server/commands/version.go

add version command for cli server

feat: add version command for cli server

---

.travis.yml

chore: deploy docker when update master or tagged

---

cmd/server/commands/utils.go
common/types/block_state.go
common/types/hash.go
consensus/active_transactions.go
consensus/block_processor.go
consensus/dpos_impl.go
consensus/election.go
consensus/votes.go
ledger/ledger.go
ledger/ledger_migration.go
ledger/ledger_test.go
ledger/ledgerstore.go
ledger/process/ledger_processor_test.go
p2p/messageMonitor.go
rpc/api/ledger.go
test/mock/mock.go

fix：solve the bug when openblock appears fork

---

.dockerignore
.travis.yml
Makefile
chain/services/ledger_service.go
ci/custom-timeout.sh
ci/deploy-docker.sh
cmd/consensus/main.go
cmd/server/commands/utils.go
cmd/server/main.go
common/genesis.go
common/genesis_test.go
config/config.go
config/defaults.go
consensus/election.go
docker/Dockerfile
docker/build.sh
ledger/ledger.go
ledger/process/ledger_processor.go
rpc/api/ledger.go
rpc/api/mintage.go
rpc/rpc_test.go
test/mock/mock.go
version.go
vm/contract/mintage.go
wallet/wallet_impl.go

split main net and test net config

---

cmd/server/commands/root.go
cmd/server/commands/utils.go
cmd/server/commands/wallet_import.go

server cli support seed, privatekey, wallet mode
N/A

feat: enhance server cli

---

config/defaults.go

chore: modify testnet bootnode address

---

cmd/server/commands/utils.go
cmd/server/commands/version.go
cmd/server/main.go

feat: configure rpc module enable

---

cmd/consensus/main.go
cmd/server/commands/root.go
cmd/server/commands/utils.go
common/util/util.go
config/config.go
config/config_manager.go
config/config_manager_test.go
config/config_test.go
config/config_v1.go
config/config_v2.go
config/defaults.go
config/migrate.go
config/migration_v1_v2.go
consensus/active_transactions.go
log/logger.go
p2p/discovery.go
p2p/discovery_test.go
p2p/messageMonitor.go
p2p/messageMonitor_test.go
p2p/node.go
p2p/streamManager_test.go
p2p/sync.go
rpc/rpc_test.go

- implement migration config interface
- refine config
- upgrade config v1 to v2
- [ x] Added tests respective to the part of code I have written.
N/A

feat: implement migration config

---

test/consensus_test.go

test: move consensus test case to test folder

---

cmd/client/commands/mintage.go
rpc/api/mintage.go
vm/contract/mintage.go

fix: mintage contract pledger amount

---

common/types/balance.go
common/types/balance_test.go
ledger/ledger.go
ledger/ledger_sms.go
ledger/ledger_sms_test.go
rpc/api/sms.go
rpc/api/util.go
rpc/apis.go

multiple block can contain the same message hash

feat: multiple block can contain the same message hash

---

config/config_v2.go
p2p/discovery_test.go
p2p/messageMonitor.go
p2p/messageMonitor_test.go
p2p/stream.go
p2p/streamManager.go
p2p/streamManager_test.go

fix: p2p bug

---

cmd/server/commands/root.go
cmd/server/commands/wallet_import.go

refactor: --config is followed by the configuration file

---

chain/services/ledger_service.go
common/genesis.go
common/genesis_test.go
ledger/ledger.go
rpc/api/ledger.go

feat：add GAS block info

---

cmd/server/commands/utils.go
rpc/rpc.go
rpc/rpc_test.go

feat: modify rpc switch

---

common/event/event_bus.go
common/event/event_bus_benchmark_test.go
common/event/event_bus_impl.go
common/event/event_bus_test.go
common/event/match.go
common/event/match_test.go

feat: implement internal event bus

---

.chglog/CHANGELOG.tpl.md
.chglog/config.yml
CHANGELOG.md

docs: rebuild change log

---

vm/vmstore/vm_store.go

fix: Query token info

---

common/profile/monitor.go
common/profile/monitor_test.go

implement timing functions
N/A

feat: implement timing functions

---

vm/contract/mintage.go
vm/contract/nep5_pledge.go

refactor: pledge time and pledge count

---

rpc/api/mintage.go
rpc/api/nep5_pledge.go
vm/contract/abi/abi_mintage.go
vm/contract/abi/abi_nep5_pledge.go

feat: add search pledge info rpc interface

---

.travis.yml

chore: only build docker image for tag branch

---

Makefile
common/genesis.go
config/config_v1.go
config/config_v2.go
config/defaults.go
log/logger.go
log/logger_debug.go
wallet/wallet_manager_impl.go

- default mainnet tag
- add debug log setting
N/A

fix: default build tags

---

cmd/server/commands/root.go
common/event/event_bus_impl.go
common/event/event_bus_test.go

fix: account mode NPE

---

vm/contract/abi/abi_nep5_pledge.go
vm/contract/mintage.go
vm/contract/mintage_config.go
vm/contract/mintage_config_testnet.go
vm/contract/nep5_pledge.go
vm/contract/nep_pledge_config.go
vm/contract/nep_pledge_config_testnet.go

feat: add nep5 chain contracts for testnet

---

common/topic.go
config/config_v2_testnet.go
consensus/active_transactions.go
consensus/block_processor.go
consensus/dpos_impl.go
p2p/discovery_test.go
p2p/messageMonitor.go
p2p/messageMonitor_test.go
p2p/streamManager.go
p2p/streamManager_test.go
p2p/sync.go
rpc/api/ledger.go
test/consensus_test.go

 refactor: eventbus topics

---

Makefile
ci/travis.codecov.sh
cmd/server/commands/root_test.go
config/config_v1.go
config/config_v1_default.go
config/config_v2.go
config/config_v2_default.go
consensus/active_transactions.go
consensus/block_processor.go
rpc/api/ledger.go
test/consensus_test.go
test/mintage_test.go
test/pledge_test.go

- clean config code
- fix update config test case

refactor: default config

---

ci/travis.codecov.sh
cmd/server/commands/root_test.go
common/time.go
common/time_test.go
go.mod
go.sum
rpc/api/mintage.go
rpc/api/nep5_pledge.go
vm/contract/mintage.go
vm/contract/mintage_config.go
vm/contract/mintage_config_testnet.go
vm/contract/nep5_pledge.go
vm/contract/nep_pledge_config.go
vm/contract/nep_pledge_config_testnet.go
vm/contract/timespan.go
vm/contract/timespan_test.go

- only run integrate test case when release
- fix calculate contract timespan

feat: npt time

---

chain/services/ledger_service.go
cmd/server/commands/root.go
cmd/server/commands/version.go
ledger/process/ledger_processor.go
rpc/api/mintage.go
rpc/api/nep5_pledge.go
test/block.go
test/mintage_test.go
test/pledge_test.go
vm/contract/abi/abi_nep5_pledge.go
vm/contract/mintage.go
vm/contract/mintage_config_testnet.go
vm/contract/nep5_pledge.go
vm/contract/nep_pledge_config.go
vm/contract/nep_pledge_config_testnet.go
vm/vmstore/vm_cache.go

- fix parse version NPE
- fix mintage log

feat: add --nobootnode to disable all bootstrap nodes

---

rpc/api/nep5_pledge.go
vm/contract/abi/abi_nep5_pledge.go
vm/contract/abi/abi_nep5_pledge_test.go
vm/contract/nep5_pledge.go
vm/vmstore/vm_store.go

feat: add rpc interface for pledge contract.

---

ledger/relation/relation.go
ledger/relation/relation_impl.go
rpc/api/sms.go

add limit to sms api

---

common/types/account.go
common/types/block_state.go
config/migration_v2_v3.go
consensus/block_processor.go
consensus/dpos_impl.go
ledger/db/badger_impl.go
ledger/ledger.go
ledger/ledger_migration.go
ledger/process/ledger_processor.go
rpc/api/ledger.go

fix: total balance calculation

---

common/types/balance.go
ledger/ledger.go
ledger/ledger_migration.go

fix: migrate ledger

---

rpc/api/nep5_pledge.go
test/pledge_test.go
vm/contract/abi/abi_nep5_pledge.go
vm/contract/nep5_pledge.go

refactor: withdraw pledge need NEP5TxId

---

cmd/server/commands/root.go
cmd/server/commands/wallet_import.go
cmd/util/util.go
config/config_manager.go

feat: cli --config supports non-existent file creation

---

cmd/server/commands/root.go
cmd/server/commands/utils.go
ledger/relation/db/dbstore.go
ledger/relation/db/dbstore_impl.go
ledger/relation/relation.go
ledger/relation/relation_impl.go

batch insert block to sqlite

---

p2p/discovery_test.go
p2p/messageMonitor.go
p2p/messageMonitor_test.go
p2p/node.go
p2p/qlcService.go
p2p/stream.go
p2p/streamManager.go
p2p/sync.go

fix: handle p2p error

---

docker/Dockerfile
docker/entrypoint.sh

feat: docker image support account/override params

---

common/topic.go
p2p/qlcService.go
p2p/streamManager.go
p2p/streamManager_test.go
rpc/api/net.go
rpc/apis.go

feat: add peersInfo rpc interface

---

ledger/process/ledger_processor.go
vm/contract/mintage.go
vm/contract/nep5_pledge.go

fix: contract empty pointer

---

config/defaults.go
config/defaults_net.go

refactor: config structure

---

cmd/server/commands/root.go

fix: configuration parameters invalid

---

cmd/client/commands/generate_test_ledger.go

feat: generate test ledger cli support designated account

---

rpc/api/nep5_pledge.go
vm/contract/abi/abi_nep5_pledge.go

feat: search pledge info via nep5Id

---

cmd/server/commands/utils.go

fix: --nobootnode bug

---

rpc/api/ledger.go
rpc/api/util.go

modify Representatives interface return

feat: modify Representatives interface return

---

Makefile

fix #344
- []Added tests respective to the part of code I have written.

feat: support build linux/arm-7

---

vm/contract/mintage_config.go
vm/contract/nep_pledge_config.go

refactor: mintage and pledge withdraw time

---

ledger/ledger.go
ledger/process/ledger_processor.go
test/mock/mock.go

feat: use ntp time when generate block

---

rpc/api/nep5_pledge.go
vm/contract/abi/abi_nep5_pledge.go
vm/contract/nep5_pledge.go
vm/vmstore/vm_store.go

remove vm field of pledge rpc module

feat: remove vm field of pledge rpc module

---

cmd/server/commands/utils.go
go.mod
go.sum
ledger/relation/db/dbstore.go
ledger/relation/db/dbstore_impl.go
ledger/relation/relation.go
ledger/relation/relation_impl.go
vm/contract/nep5_pledge.go

feat: batch update block to sqlite

---

ledger/process/ledger_processor.go

update pending for contract block

feat: update pending for contract block

---

ledger/ledger.go
rpc/api/ledger.go

- set generate block interface privatekey optional
- fix #333 

feat: set generate block interface privatekey optional

---

common/topic.go
common/types/block_state.go
consensus/block_processor.go
consensus/dpos_impl.go
ledger/ledger.go
ledger/process/ledger_processor.go
ledger/relation/relation_impl.go
p2p/qlcService.go
p2p/sync.go

-  feat:  add vote cache
-  feat:  if the node is synchronizing, the synchronization will not be repeated
-  fix:    openblock judgment logic
-  feat: need to send a confirmation notice if block from sync

fix: sync bug

---

chain/services/p2p_service.go
common/event/event_bus.go
common/event/event_bus_benchmark_test.go
common/event/event_bus_impl.go
common/event/event_bus_test.go
common/event/event_handlers.go
common/event/event_handlers_test.go
consensus/dpos_impl.go
go.mod
go.sum
p2p/qlcService.go

- fix #308 
- fix #352
=### Type
N/A

feat: event bus support buff

---

ledger/relation/relation_impl.go
rpc/api/rewards.go

feat: add chan to sqlite

---

ledger/process/ledger_processor.go
ledger/relation/relation_impl.go

remove work/sign check for Rewards contractblock

feat: remove work/sign check for Rewards contractblock

---

consensus/dpos_impl.go
rpc/api/net.go

fix: find online representative bug

---

ledger/process/ledger_processor.go

fix: contract reward block check error

---

common/event/event_bus.go
common/event/event_bus_impl.go
common/event/event_bus_test.go
p2p/qlcService.go
rpc/api/net.go

feat: eventbus support sync subscribe

---

common/types/block_state.go
ledger/ledger.go
ledger/ledger_test.go
ledger/process/ledger_processor_test.go
mock/mock.go

 feat: modify stateblock parent

---

ledger/ledger.go
test/consensus_test.go
vm/contract/abi/abi_nep5_pledge.go

fix: integrate test case error

---

vm/contract/rewards.go

fix: generate reward block pending

---

vm/contract/rewards.go

fix: QGAS rewards balance

---

ledger/process/ledger_processor.go
vm/vmstore/vm_store.go

feat: add log to ledger

---

vm/contract/nep5_pledge.go

fix: pledge DoReceive bug

---

rpc/api/rewards.go
vm/contract/rewards.go

- implement confidant/airdrop detail interface
- fix reward type

feat: implement query rewards details RPC

---

ledger/process/ledger_processor.go
vm/contract/abi/abi_mintage.go

fix: process fork for cotractreward block

---

vm/contract/abi/abi_rewards_test.go

test: add parse rewards info testcase

---

ci/travis.codecov.sh
common/types/unchecked.go
ledger/ledger.go
ledger/ledger_test.go
ledger/process/ledger_processor.go
ledger/process/ledger_processor_test.go
p2p/stream.go
rpc/api/account.go
rpc/api/ledger.go
rpc/api/mintage.go
rpc/api/nep5_pledge.go
rpc/api/rewards.go
rpc/api/sms.go
rpc/api/wallet.go
test/block.go
test/block_test.go
test/mintage_test.go
test/pledge_test.go
trie/trie.go
trie/trie_test.go
vm/contract/abi/abi_rewards_test.go
vm/vmstore/vm_store_test.go

- test: add ledger_process testcase and rewards and vm store test case
- fix: encode trie
- feat: judge pledge amount and modify get all uncheckblock
- fix: balance check when process block bug
- fix: generate send balance

fix: v1.2.0 bug

---

rpc/api/rewards.go

fix: possible NPE

---

ledger/ledger.go

fix: random block bug

---

rpc/api/account.go
rpc/api/net.go
rpc/api/rewards.go
test/generateChain.go
test/verifier_test.go

- format code
- fix generate hash when verify reward send sign
N/A

fix: verify rewards sign

---

vm/contract/abi/abi_mintage.go

fix: cpu high loading when query token info

---

rpc/rpc.go

fix: websocket CORS

---

vm/contract/abi/abi_rewards.go

refactor: make rewards exception log clearer

---

consensus/active_transactions.go

feat: delete unchecked block depend on forked block

---

consensus/active_transactions.go

fix: delete unchecked block bug

---

ledger/process/ledger_processor.go

feat: change ledger verifier CheckBlock map to local variable

feat: change ledger verifier CheckBlock map to local variable

---

common/convert.go
rpc/api/util.go

feat: modify RawToBalance interface

 feat: modify RawToBalance interface

---

rpc/api/ledger.go

define account balance return struct

feat: define account balance return struct

---

cmd/server/commands/root.go
cmd/server/commands/root_test.go

fix: configParms bug

---

p2p/messageMonitor.go
p2p/stream.go
p2p/streamManager.go
p2p/streamManager_test.go
p2p/sync.go

feat: add peer connect status judge when syncing

---

rpc/api/ledger.go
rpc/api/mintage.go
rpc/api/nep5_pledge.go
rpc/api/rewards.go

fix: null pointer bug with rpc interface

---

go.mod
go.sum
ledger/db/badger_impl.go
ledger/db/badger_impl_test.go
ledger/db/badger_performance_test.go
ledger/db/dbstore.go
ledger/ledger.go
ledger/ledger_migration.go
ledger/ledger_pov.go
vm/vmstore/vm_store.go
wallet/wallet_impl.go
wallet/wallet_manager_impl.go

fix: badger go mod dep

---

p2p/streamManager.go

fix: write twice to messagechan

---

.travis.yml
cmd/rpc/main.go
common/types/unchecked.go
consensus/dpos/active_transactions.go
ledger/ledger.go
ledger/ledger_test.go
ledger/ledgerstore.go
ledger/process/ledger_processor.go
ledger/process/ledger_processor_test.go
ledger/process/verifier.go
rpc/api/ledger.go
vm/contract/abi/abi_rewards.go
vm/vmstore/vm_store.go

- rollback for contract block fix #400

feat: rollback contract block 

---

p2p/stream.go
p2p/streamManager.go

fix: channel blocked in sendMessageToPeer func

---

test/consensus_test.go

fix: consensus testcase

---

go.mod
go.sum
p2p/bootstrap.go
p2p/bootstrap_test.go
p2p/discovery.go
p2p/node.go
p2p/stream.go
p2p/streamManager.go

chore: update libp2p package

---

cmd/client/commands/mintage.go
cmd/client/commands/pledge.go
crypto/random/random.go
crypto/random/random_test.go

fix: nep5txid encoding/hex error

---

consensus/dpos/dpos_impl.go

do not check pov sync state if pov service is not enabled

fix: do not check pov sync state if pov service is not enabled

---

ledger/process/ledger_processor.go
trie/trie.go
vm/vmstore/vm_store.go

feat: don't save contract data when block check

---

config/config.go
config/config_manager_test.go
config/defaults.go

feat: update libp2p package

---

ledger/relation/relation_impl.go
p2p/dispatcher.go
p2p/messageMonitor.go
p2p/node.go
p2p/stream.go
p2p/sync.go

remove useless time sleep to reduce cpu usage.
tests have done in linux/windows/macos.

feat: remove useless time sleep to reduce cpu usage

---

test/block_testnet.go
test/transaction_test.go

refactor: transaction test case

---

consensus/dpos/processor.go
ledger/ledger.go
ledger/process/ledger_processor.go

fix: badger transaction conflict.

---

ledger/ledger.go

fix:  ledger goroutine not stop when ledger closed

---

consensus/dpos/active_transactions.go
consensus/dpos/dpos_impl.go
consensus/dpos/processor.go
ledger/process/ledger_processor.go
test/openfork_test.go
test/transaction_test.go

test: add openfork and bulk transaction test cases

---

p2p/messageMonitor.go

fix: the transaction cannot be confirmed when the representative re online

---

common/params_pov.go
common/params_pov_testnet.go
consensus/dpos/processor.go

If roots has added block, the confirmReq will not get confirmAck.

fix: confirmReq may not get confirmAck

---

ledger/ledger.go
ledger/ledger_migration.go

fix: add block child error

---

p2p/messageMonitor.go
test/verifier_test.go

refactor: use context exit goroutine

---

consensus/dpos/active_transactions.go
consensus/dpos/dpos_impl.go
consensus/dpos/election.go
consensus/dpos/processor.go

fix: optimize the voting process

---

ledger/process/ledger_processor.go

fix: accountMetaCache may be not the newest

---

cmd/server/commands/root.go
cmd/server/commands/utils.go

fix: auto generate receive block may not be correct

---

rpc/api/ledger.go

getBlockInfo amount param miss

fix: getBlockInfo amount param miss

---

ledger/ledger.go
ledger/process/ledger_processor.go
p2p/messageMonitor.go
rpc/api/ledger.go

fix: some rpc interface return incorrect info

---

ledger/ledger.go
ledger/process/ledger_processor.go
test/block.go
test/blockCacheRollback_test.go

fix: rollback block cache

---

consensus/pov/pov_chain.go
consensus/pov/pov_chain_test.go
consensus/pov/pov_event.go
consensus/pov/pov_impl.go
consensus/pov/pov_processor.go
consensus/pov/pov_processor_test.go
consensus/pov/pov_txpool.go
consensus/pov/pov_txpool_test.go
consensus/pov/pov_verifier_test.go
ledger/ledger_pov_test.go
mock/mock_pov.go

- Add some pov uint testcase.
- fix #447 

test: add pov unit testcase (#447)

---

common/types/block_state.go
go.mod
go.sum
ledger/process/ledger_processor.go
test/transaction_test.go

refactor: block rollback

---

ledger/ledger.go
ledger/process/ledger_processor.go
rpc/api/ledger.go

fix: transaction conflict may happen in ledger process

---

chain/services/miner_service.go
chain/services/pov_service.go
cmd/client/commands/miner_history.go
cmd/client/commands/miner_reward.go
cmd/client/commands/pledge.go
common/event/event_bus.go
common/event/event_bus_impl.go
common/event/event_bus_test.go
consensus/dpos/dpos_impl.go
consensus/pov/pov_chain.go
consensus/pov/pov_fake.go
consensus/pov/pov_pow.go
consensus/pov/pov_sync.go
consensus/pov/pov_verifier.go
ledger/ledger.go
ledger/ledger_migration.go

- format code
- upgrade ledger version
n/a

feat: upgrade ledger to v7

---

cmd/client/commands/generate_test_pair.go
common/topic.go
common/types/block_pov.go
consensus/pov/pov_impl.go
consensus/pov/pov_sync.go
consensus/pov/pov_sync_peer.go
consensus/pov/pov_sync_pool.go
p2p/messageMonitor.go
p2p/stream.go
p2p/streamManager.go

#448 optimize pov sync using internal queue
#449 add pov cyclic synchronous  

feat: pov sync v2

---

ledger/db/badger_impl.go
ledger/ledger.go
ledger/ledger_migration.go
wallet/wallet_impl.go

feat: migrate ledger to v7

---

ledger/ledger.go
ledger/ledger_cache.go
ledger/ledger_cache_test.go
rpc/api/debug.go

feat: refactor ledger cache

---

common/types/account.go
common/types/benefit.go
common/types/generic.go
common/types/unchecked.go
go.mod
go.sum
ledger/ledger.go
ledger/ledger_generic.go
ledger/ledger_migration.go
ledger/ledger_pov.go
ledger/ledger_test.go
ledger/ledgerstore.go
ledger/process/ledger_processor.go
rpc/api/ledger.go
wallet/wallet_impl.go

generate CURD code automatically 
fix #526 

feat: generate CURD code automatically

---

p2p/messageMonitor.go

fix: need rollback when blockcache fork

---

p2p/messageMonitor.go
p2p/stream.go

chore：change log level for p2p message timeout

---

ledger/process/ledger_processor.go
p2p/messageMonitor.go

fix: link repeat

---

rpc/api/ledger.go

feat: sort query pending by timestamp

---

consensus/receiver.go

fix: invalid ack

---

common/params_confidant.go
consensus/receiver.go

fix: enlarge confidant cache size

---

common/types/unchecked.go
ledger/ledger.go
ledger/ledger_test.go
ledger/process/ledger_processor.go
p2p/messageMonitor.go
test/pending_test.go

 feat: add pending meta

---

ledger/process/ledger_processor.go

send block should not check Repeated

fix: send block should not check Repeated

---

chain/services/rollback_service.go
chain/services/rollback_service_test.go
cmd/server/commands/root.go
cmd/server/commands/utils.go
ledger/ledger.go
ledger/process/ledger_processor.go
test/pledge_test.go

- refactor block cache rollback 
- add rollback service
- UpdatePending return nil when pending not found

refactor: cache block rollback

---

ledger/ledger.go
ledger/ledger_test.go
ledger/process/ledger_processor.go
rpc/api/ledger.go

fix: use RWMutex ensure blockcache thread safe

---

consensus/dpos/processor.go

fix: rollback cache if forked

---

ledger/ledger.go
ledger/ledger_migration.go

feat: migrate ledger v7 to v8

---

consensus/dpos/processor.go

fix: fix rollback bug

---

ledger/ledger_migration.go
ledger/process/ledger_processor.go

delete account cache when ledger migrate

feat: delete account cache when ledger migrate

---

chain/context/chain_context.go
chain/helper.go
chain/helper_test.go
chain/metrics_service.go
chain/metrics_service_test.go
config/config.go
config/config_v5.go
config/defaults_net.go
config/migration_v4_v5.go
config/migration_v4_v5_test.go
go.mod
go.sum
monitor/cpu.go
monitor/cpu_test.go
monitor/disk.go
monitor/influxdb/influxdb.go
monitor/metrics.go
monitor/metrics_test.go
monitor/net.go

feat: implement metrics service

---

CHANGELOG.md
Makefile
crypto/ecies/ecies_test.go
go.mod
go.sum
p2p/dispatcher.go
p2p/messageMonitor.go

fix: message cache chan blocking

---

CHANGELOG.md
Makefile
go.mod
p2p/dispatcher.go
p2p/messageMonitor.go

feat: merge v1.2.6.6

---

CHANGELOG.md
Makefile
chain/context/chain_context.go
chain/context/chain_context_test.go
chain/rpc_service.go
common/service_test.go
config/config_v1_default.go
config/config_v1_testnet.go
config/config_v2_default.go
config/config_v2_testnet.go
config/defaults.go
go.mod
go.sum
log/log_service.go
p2p/discovery_test.go
p2p/dispatcher.go
p2p/messageMonitor.go
p2p/messageMonitor_test.go
p2p/qlcService.go
p2p/streamManager_test.go
rpc/api/ledger_test.go
test/blockCacheRollback_test.go
test/consensus_test.go
test/openfork_test.go
test/pending_test.go
test/pledge_test.go
test/test_helper.go
test/transaction_test.go

- fix default IPC endpoint
- fix integration test cases
- chain context support wait for all service started
N/A

refactor: chain context

---

cmd/server/commands/root.go
config/config_manager.go
config/config_manager_test.go
config/config_v4.go
config/config_v5.go
config/defaults_testnet.go
config/migration_v4_v5_test.go

- fix config version
- add admin token to config

refactor: config manager support batch update params

---

Makefile
cmd/client/commands/dump_ledger.go
cmd/client/commands/root.go
cmd/main.go
ledger/ledger_account.go
ledger/ledger_account_test.go
ledger/ledger_dump.go
ledger/ledger_dump_test.go
rpc/api/debug.go

- support dump ledger into relation db , fix #511 
- combine server and client cli to one build file , fix #533 

feat: add cli to dump ledger & combine  cli 

---

go.sum
monitor/disk.go
rpc/api/metrics.go
rpc/api/metrics_test.go
rpc/apis.go

feat: implement metrics rpc

---

.github/workflows/go.yml
chain/autoreceive_service.go
chain/chainmanage_service.go
common/event/event_bus.go
common/event/event_bus_impl.go
common/event/event_bus_test.go
common/event/event_handlers.go
common/event/event_handlers_test.go
consensus/dpos/dpos_impl.go
consensus/pov/pov_impl.go
consensus/pov/pov_processor.go
consensus/pov/pov_sync.go
consensus/receiver.go
ledger/relation/relation_impl.go
miner/miner.go
p2p/qlcService.go
rpc/api/net.go
rpc/api/pov.go

fix: can not unsubscribe handler
N/A

fix: unsubscribe event

---

rpc/api/contract.go
vm/contract/abi/abi_blackhole.go
vm/contract/abi/abi_miner.go
vm/contract/abi/abi_mintage.go
vm/contract/abi/abi_nep5_pledge.go
vm/contract/abi/abi_rewards.go
vm/contract/contract.go

- add api to get abi by contract address  

feat: add api to get abi by contract address

---

go.mod
go.sum
rpc/api/ledger.go
rpc/api/ledger_test.go
rpc/api/subscribe.go

- implement rpc pubsub ,fix #399 

feat: implement rpc pubsub

---

ledger/ledger_dump_test.go
p2p/messageMonitor.go
p2p/sync.go

fix: only one gorouting can handle the pullrequest at the same time

---

p2p/node.go
p2p/node_test.go
p2p/stream.go
p2p/streamManager.go

fix: delete netAttribute

---

go.mod
go.sum

chore: upgrade jsonrpc version

---

consensus/dpos/dpos_impl.go
consensus/pov/pov_chain.go
consensus/pov/pov_sync.go

fix: confidant bug

---

.goreleaser.yml
Makefile
chain/autoreceive_service.go
chain/consensus_service.go
chain/context/chain_context_test.go
chain/version/version.go
chain/version/version_test.go
cmd/client/commands/version.go
cmd/server/commands/root.go
cmd/server/commands/version.go
ledger/db/badger_impl.go
ledger/db/dbstore.go
ledger/ledger.go
ledger/process/cache_processor.go
ledger/process/ledger_processor.go
rpc/api/chain.go
rpc/api/ledger.go
rpc/apis.go

- check contract receive block pending
- add sdk to get badger size
- add sdk to get chain version

feat: check contract receive block pending

---

ledger/ledger.go
mock/mock_pov.go
rpc/api/black_hole.go
rpc/api/ledger.go
rpc/api/ledger_test.go
rpc/api/mintage.go
rpc/api/nep5_pledge.go
rpc/api/rewards.go
rpc/api/rewards_test.go
rpc/apis.go
test/generate_chain.go

feat: add pov height to block

---

cmd/client/commands/debug.go
cmd/client/commands/debug_povinfo.go
cmd/client/commands/pov_mininginfo.go
cmd/client/commands/root.go
cmd/client/commands/version.go
cmd/server/commands/root.go
cmd/server/commands/version.go
consensus/pov/consensus_pov.go
consensus/pov/pov_chain.go
consensus/pov/pov_chain_test.go
consensus/pov/pov_fake.go
consensus/pov/pov_impl.go
consensus/pov/pov_pow.go
consensus/pov/pov_processor.go
consensus/pov/pov_sync.go
consensus/pov/pov_sync_pool.go
consensus/pov/pov_txpool.go
ledger/db/badger_impl.go
ledger/process/ledger_processor.go
miner/pov_worker.go
mock/mock_pov.go
p2p/node.go
p2p/node_test.go
p2p/stream.go
rpc/api/debug.go
rpc/api/pov.go
trie/node_pool.go

1.remove pov builtin cpu mining to fix #641;
2.list of accountTxs in PovTxPool struct has no toplimit to fix #416;
3.add pov debug info rpc & cmd;

feat: optimize pov mining & debug info

---

ledger/process/rollback.go
ledger/process/rollback_test.go

- fix rollback cache account bug

fix: rollback cache account

---

consensus/pov/pov_sync.go
consensus/pov/pov_sync_peer.go
consensus/pov/pov_sync_pool.go

feat: add more pov sync debug info

---

cmd/client/commands/miner_reward.go
cmd/client/commands/rep_reward.go
consensus/dpos/dpos_impl.go
consensus/dpos/online.go
consensus/dpos/processor.go
ledger/ledger_pov.go
rpc/api/miner.go
rpc/api/pov.go
rpc/api/representative.go
vm/abi/type.go
vm/contract/abi/abi_miner.go
vm/contract/abi/abi_representative.go
vm/contract/miner.go
vm/contract/representative.go

add new fileds to reward contract data

fix: change reward contract data

---

common/params_pov.go
common/params_pov_testnet.go
common/types/block_pov.go
consensus/pov/pov_chain.go
consensus/pov/pov_chain_test.go
consensus/pov/pov_processor.go
consensus/pov/pov_processor_test.go
consensus/pov/pov_sync.go
consensus/pov/pov_sync_pool.go
consensus/pov/pov_sync_test.go
consensus/pov/pov_verifier.go

1.optimize pov tx pending check.
2.modify pov max fork height.

fix: optimize pov tx pending check

---

p2p/sync.go

fix: frontier not found when syncing

---

consensus/pov/pov_sync.go
consensus/pov/pov_sync_pool.go
rpc/api/pov.go
rpc/api/pov_pubsub.go
rpc/api/pov_test.go

add pov pubsub for new blocks.

feat: add pov pubsub for new blocks

---

p2p/messageMonitor.go
p2p/node.go

fix: resend  block in the blockcache

---

consensus/dpos/dpos_impl.go
p2p/messageMonitor.go
p2p/streamManager.go
p2p/sync.go

fix: problem with the logic of picking node when syncing

---

ledger/process/ledger_processor.go
vm/contract/blackhole.go
vm/contract/contract.go
vm/contract/miner.go
vm/contract/mintage.go
vm/contract/nep5_pledge.go
vm/contract/representative.go
vm/contract/rewards.go

feat: add contract describe

---

consensus/dpos/processor.go

fix: confirm-chain process may exit abnormally

---

chain/version/version.go
chain/version/version_test.go
cmd/client/commands/pledge_withdraw.go
cmd/main.go
cmd/server/commands/root.go

print QLCChain ascii log and node version when node start
N/A

feat: add ascii logo

---

ledger/process/sync_processor.go

- can not update contract reward block data

fix:  can not update contract reward block data

---

consensus/pov/pov_chain.go
consensus/pov/pov_chain_test.go
consensus/pov/pov_event.go
consensus/pov/pov_impl.go
consensus/pov/pov_pow.go
consensus/pov/pov_processor.go
consensus/pov/pov_processor_test.go
consensus/pov/pov_state.go
consensus/pov/pov_sync.go
consensus/pov/pov_sync_peer.go
consensus/pov/pov_sync_pool.go
consensus/pov/pov_sync_test.go
consensus/pov/pov_txpool.go
consensus/pov/pov_txpool_test.go
consensus/pov/pov_verifier.go
consensus/pov/pov_verifier_test.go

chore: golangci lint consensus pov

---

rpc/api/debug.go
rpc/api/ledger.go
rpc/api/subscribe.go

feat: add pub/sub debug interface

---

rpc/api/ledger.go
rpc/api/pov.go
rpc/api/pov_pubsub.go
rpc/api/subscribe.go

pubsub channel blocked by lots state block event.

fix: pubsub channel blocked

---

consensus/pov/pov_chain.go
consensus/pov/pov_processor.go
consensus/pov/pov_sync_pool.go
consensus/pov/pov_txpool.go
consensus/pov/pov_verifier.go
ledger/ledgerstore.go
rpc/api/pov.go

pov should check confirmed state blocks.

fix: pov should check confirmed state blocks

---

consensus/dpos/processor.go

fix: process syncronized blocks while pulling

---

ledger/ledger_account.go

fix: invalid data when call smart contract

---

rpc/api/ledger.go
rpc/api/pov.go

pubsub should remove chan when notify error.

fix: pubsub should remove chan when notify error

---

rpc/api/ledger.go

fix: wait for the previous block to confirm before broadcasting

---

cmd/client/commands/miner.go
cmd/client/commands/miner_recvpend.go
cmd/client/commands/miner_reward.go
cmd/client/commands/pov.go
cmd/client/commands/pov_blockinfo.go
cmd/client/commands/pov_minerstats.go
cmd/client/commands/pov_repstats.go
cmd/client/commands/pov_txinfo.go
cmd/client/commands/root.go
cmd/client/commands/tx.go
cmd/client/commands/tx_blockinfo.go
consensus/pov/pov_chain.go
ledger/db/badger_impl.go
ledger/db/badger_impl_test.go
ledger/db/dbstore.go
ledger/ledger.go
ledger/ledger_migration.go
ledger/ledger_pov.go
ledger/ledger_pov_test.go
ledger/ledgerstore.go
rpc/api/pov.go
rpc/api/pov_test.go
rpc/api/rewards_test.go

optimize pov txlookup using batch write.
fix #693 

feat: optimize pov txlookup using batch write

---

rpc/api/ledger.go

fix: openblock does not exit previous block

---

cmd/client/commands/miner.go
cmd/client/commands/miner_recvpend.go
cmd/client/commands/miner_reward.go
cmd/client/commands/pov.go
cmd/client/commands/pov_blockinfo.go
cmd/client/commands/pov_minerstats.go
cmd/client/commands/pov_repstats.go
cmd/client/commands/pov_txinfo.go
cmd/client/commands/root.go
cmd/client/commands/tx.go
cmd/client/commands/tx_blockinfo.go
consensus/pov/pov_chain.go
ledger/db/badger_impl.go
ledger/db/badger_impl_test.go
ledger/db/dbstore.go
ledger/ledger.go
ledger/ledger_migration.go
ledger/ledger_pov.go
ledger/ledger_pov_test.go
ledger/ledgerstore.go
rpc/api/pov.go
rpc/api/pov_test.go
rpc/api/rewards_test.go

feat: pov txlookup merge

---

log/logger.go

refactor: change default logger timestamp encoder

---

consensus/dpos/processor.go
rpc/api/ledger.go

feat: broadcast the block when check result is progress

---

cmd/client/commands/miner.go
cmd/client/commands/miner_getinfo.go
cmd/client/commands/pov_minerstats.go
cmd/client/commands/pov_repstats.go
rpc/api/pov.go

fix pov rep & miner stats.
add pov miner info cmd.

fix: pov rep and miner stats

---

rpc/api/ledger.go

refactor: process block logic

---

consensus/dpos/dpos_impl.go
consensus/dpos/dpos_impl_test.go
consensus/dpos/processor.go

fix: ack sign error

---

common/types/target.go

fix: pov pubsub crash

---

consensus/dpos/dpos_impl.go
consensus/dpos/processor.go
ledger/process/ledger_processor.go
ledger/process/sync_processor.go

refactor: block sync done log

---

rpc/api/debug.go
rpc/api/ledger.go
rpc/api/ledger_test.go
rpc/api/pov.go
rpc/api/pov_pubsub.go
rpc/api/pov_test.go
rpc/api/subscribe.go
rpc/apis.go

- pubsub subscript chain event

feat: pubsub subscript chain event

---

vm/contract/miner.go
vm/contract/representative.go

fix: reward pending err

---

consensus/dpos/dpos_impl.go

fix: process sync cache multiple times

---

ledger/ledger_cache.go
ledger/ledger_pending.go
ledger/process/rollback.go
rpc/api/debug.go
rpc/apis.go

fix: eventbus parameter to debug api

---

consensus/dpos/dpos_impl.go
consensus/dpos/processor.go

fix: local rep vote for frontier

---

rpc/api/ledger.go
rpc/api/subscribe.go

- add account block pubsub api

feat: add account block pubsub api

---

cmd/client/commands/tx_blockinfo.go
cmd/util/util.go
rpc/api/ledger.go
rpc/api/pov.go

pov_getMinerStats return 0 miner.

fix: pov minerstats

---

go.sum
p2p/node.go
p2p/sync.go

chore: update the sync log print

---

consensus/dpos/active_transactions.go
consensus/dpos/processor.go
ledger/process/rollback.go
rpc/api/debug.go

- update cache account when rollback cache block

fix: update cache account when rollback cache block

---

consensus/dpos/active_transactions.go
consensus/dpos/dpos_impl.go
consensus/dpos/dpos_impl_test.go
consensus/dpos/processor_test.go

fix: Do not rollback when the vote times out

---

ledger/process/rollback.go

feat: rollback block cache

---

chain/context/chain_context.go
chain/helper.go
chain/resendblock_service.go
common/topic.go
ledger/process/rollback.go
p2p/messageMonitor.go
rpc/api/ledger.go

feat: use a service resend and rollback block

---

chain/resendblock_service.go

fix: hotfix resend bug

---

cmd/client/commands/pov.go
cmd/client/commands/pov_minerstats.go
cmd/client/commands/pov_repstate.go
rpc/api/pov.go

add pov rep state;
add reward in pov getMinerStats;

feat: add pov rep state and miner reward

---

config/config_manager_test.go
config/config_v2_default.go
config/config_v2_testnet.go
p2p/discovery.go
p2p/discovery_params.go
p2p/discovery_params_testnet.go
p2p/streamManager_test.go

feat: open mdns

---

cmd/client/commands/pov_repstats.go
consensus/pov/pov_state.go
rpc/api/pov.go

add more infos to pov_getRepStat  rpc

feat: change pov_getRepStat rpc

---

cmd/client/commands/pov_blockinfo.go
cmd/server/commands/purgepov.go
cmd/server/commands/removedb.go
cmd/server/commands/root.go
rpc/api/pov.go

feat: add purge pov cmd

---

chain/ledger_service.go

fix: genesis block can not be stored in the ledger

---

ledger/process/cache_processor.go
ledger/process/ledger_check.go
ledger/process/ledger_processor.go
ledger/process/rollback.go
ledger/process/sync_processor.go
rpc/api/ledger.go
vm/contract/nep5_pledge.go

- refactor block check, fix #748 

feat: refactor block check

---

common/genesis.go

fix: genesis Mintage block should also be genesis block

---

chain/ledger_service.go
common/genesis.go

fix: genesis blocks ledger cache is incorrect

---

rpc/api/ledger.go

- pubsub not return new account pending

fix: pubsub not return new account pending

---

consensus/dpos/dpos_impl.go
ledger/db/badger_impl.go
ledger/db/badger_impl_test.go
ledger/db/dbstore.go
ledger/ledger.go
ledger/ledger_cache_test.go
ledger/ledger_represention_test.go
ledger/process/rollback.go
ledger/process/rollback_test.go
ledger/process/sync_processor.go
mock/mock_contract.go
mock/mock_contract_testnet.go
rpc/api/representative.go
trie/trie.go
trie/trie_iterator_test.go
trie/trie_test.go
vm/vmstore/vm_cache.go
vm/vmstore/vm_store.go
vm/vmstore/vm_store_test.go

- rollback contract data
- fix rollback contract reward block

fix: rollback contract data

---

ledger/process/rollback.go

- fix: rollback contract data in contract block
- fix #794 

fix: rollback contract data in contract block

---

cmd/client/commands/pov.go
cmd/client/commands/pov_daystats.go
common/genesis_pov.go
common/genesis_pov_test.go
common/params_pov.go
common/params_pov_testnet.go
common/types/block_pov.go
common/types/block_pov_gen.go
common/types/block_pov_gen_test.go
common/types/state_pov.go
common/types/target.go
consensus/pov/pov_chain.go
consensus/pov/pov_verifier.go
consensus/pov/pov_verifier_test.go
ledger/ledger.go
ledger/ledger_pov.go
ledger/ledger_pov_test.go
ledger/ledgerstore.go
miner/pov_worker.go
rpc/api/pov.go

update pov mining reward and difficulty statistics. 

feat: update pov mining reward and difficulty statistics

---

common/genesis_pov.go
common/genesis_pov_test.go
common/genesis_pov_testnet_test.go
common/params_pov.go

modify pov mainnet genesis difficulty.  

fix: modify pov mainnet genesis difficulty

---

ledger/ledger_dump_test.go
p2p/sync.go

fix: fork when syncing 

---

Makefile
go.mod
go.sum
ledger/process/ledger_processor.go
vm/contract/mintage.go
vm/contract/nep5_pledge.go

fix: check contract reward block pending

---

consensus/pov/pov_chain_test.go
consensus/pov/pov_processor.go
consensus/pov/pov_state.go
mock/mock.go

optimize pov state using trie cache.  

feat: optimize pov state using trie cache

---

consensus/pov/pov_chain.go
consensus/pov/pov_state.go
go.mod

pov chain remove global trie tree cache.  

fix: pov chain remove global trie tree cache

---

consensus/dpos/active_transactions.go
consensus/dpos/dpos_impl.go
consensus/dpos/election.go
consensus/dpos/processor.go
consensus/utils.go
go.mod
vm/contract/nep5_pledge.go
vm/vmstore/vm_store.go

fix: check the synced blocks normally

---

cmd/client/commands/pov.go
cmd/client/commands/pov_blockinfo.go
cmd/client/commands/pov_tdinfo.go
common/genesis_pov_testnet.go
common/genesis_pov_testnet_test.go
common/params_pov.go
common/params_pov_testnet.go
consensus/pov/pov_chain.go
consensus/pov/pov_pow.go
rpc/api/pov.go

update pov testnet param;
change pow work sum calculation;

feat: pov testnet param

---

p2p/node.go

feat: update p2p version to 8

---

Makefile

chore: fetch latest git tag as version

---

rpc/api/ledger.go

fix: process bug

---

.github/workflows/go-qlc-builder.yml
Makefile
docker/Dockerfile
docker/Dockerfile_builder

- add cron job to build go-qlc-builder
- update build runtime

chore: update dependencies

---

consensus/dpos/dpos_impl.go

fix: sync finish bug

---

p2p/node.go
p2p/stream.go
p2p/streamManager.go

fix: find node with the higher version to synchronize

---

cmd/client/commands/pledge.go
cmd/client/commands/pledge_getinfo.go
cmd/client/commands/pledge_withdraw.go
cmd/client/commands/pov_daystats.go

update pov daystats cmd;
add pledge info cmd;

feat: pov cmd infostats

---

cmd/server/commands/removedb.go
cmd/server/commands/root.go
common/params.go
config/defaults.go

remove testmode global flag.  

fix: remove testmode global flag

---

p2p/node.go

fix: bug of online peers

---

rpc/api/pov.go

add pov checkAllAccountStates rpc.  

fix: add pov checkAllAccountStates rpc

---

chain/resendblock_service.go

fix: memory leak of resendblock service

---

chain/context/chain_context.go
common/event/event_manager.go
common/event/feed.go
common/event/feed_event_bus.go
common/event/feed_event_bus_test.go
common/event/feed_test.go
common/topic/messages.go
consensus/dpos/dpos_impl.go
consensus/pov/pov_impl.go
miner/miner.go
miner/pov_worker.go
rpc/api/debug.go
rpc/api/pov.go
rpc/apis.go

feat: event feed using channel

---

common/params_pov.go
common/params_pov_testnet.go
common/types/block_pov.go
common/types/block_pov_btc.go
common/types/hash.go
common/types/pov_algo.go
consensus/pov/pov_chain.go
consensus/pov/pov_verifier.go
miner/pov_worker.go

chore: merge branch algo-hybrid.

chore: merge branch algo-hybrid

---

chain/pov_service.go
common/statedb/pov_statedb.go
common/statedb/pov_statedb_test.go
consensus/dpos/dpos_test.go
consensus/pov/consensus_pov_test.go
consensus/pov/pov_impl.go
consensus/pov/pov_impl_test.go
consensus/pov/pov_sync_test.go
consensus/pov/pov_txpool.go
consensus/pov/pov_txpool_test.go
consensus/pov/pov_verifier_test.go
ledger/ledger_pov_test.go
mock/mock.go
mock/mock_pov.go
rpc/api/pov_test.go
rpc/api/public_key_distribution.go
vm/contract/public_key_distribution.go

add pov unit test case for consunses, ledger. 

test: add pov unit test case

---

consensus/pov/pov_sync_pool.go

pov sync can not finished but sync queue is fulled. 
fix #856 

fix: pov sync can not finished but sync queue is fulled

---

chain/ledger_service.go
chain/ledger_service_test.go
cmd/server/commands/root.go
config/config_v6.go
consensus/dpos/dpos_test.go
consensus/dpos/eletion_test.go
ledger/ledger_test.go
ledger/process/ledger_processor_test.go
mock/mock.go
rpc/api/api_test.go
rpc/api/ledger_test.go
vm/contract/blackhole_test.go
vm/contract/contract_test.go
vm/contract/settlement_test.go

refactor: type of genesis account stored in configuration file

---

mock/block.go
mock/bock_testnet.go
rpc/api/settlement.go
vm/contract/abi/abi_settlement.go
vm/contract/abi/abi_settlement_gen.go
vm/contract/abi/abi_settlement_gen_test.go
vm/contract/abi/abi_settlement_test.go
vm/contract/contract.go
vm/contract/settlement.go
vm/contract/settlement_test.go

- fix #921 
- fix #923
- fix calculate SMS sending success rate

feat: support multi-party settlement invoice

---

vm/contract/abi/abi_settlement.go
vm/contract/abi/abi_settlement_gen.go
vm/contract/abi/abi_settlement_test.go

refactor: calculate matching SMS rate

---

cmd/server/commands/removedb.go
common/storage/db/badger.go
consensus/pov/pov_chain.go
ledger/ledger_pov.go
ledger/ledger_pov_test.go

pov should not reset chain in default.

fix: pov should not reset chain in default

---

rpc/api/settlement.go

feat: add settlement_getCDRStatusByCdrData interface

---

p2p/node.go

feat: disable message signature in pubsub

---

config/config_manager.go
config/genesis.go
config/genesis_test.go
config/migration_v5_v6_test.go

refactor: get genesis info interface

---

rpc/api/ledger.go
rpc/api/ledger_test.go

feat: add genesis info rpc interface

---

mock/mock_pov.go
vm/contract/public_key_distribution_test.go

test: add dpki reward testcase.

test: add dpki reward testcase

---

common/servicestatus_string.go
rpc/api/mock_block_mainnet_test.go
rpc/api/mock_block_testnet_test.go
rpc/api/public_key_distribution_test.go
rpc/api/settlement.go
rpc/api/settlement_test.go
vm/contract/abi/abi_settlement.go
vm/contract/abi/abi_settlement_gen.go
vm/contract/abi/abi_settlement_gen_test.go
vm/contract/abi/abi_settlement_test.go
vm/contract/settlement.go
vm/contract/settlement_test.go

- refine terminate settlement contract
- add query pre/next stop names interface
- fix #956 
- fix #957 

feat: add query settlement stop names interface

---

rpc/api/ledger.go
rpc/api/ledger_test.go

- fix #963 
- refactor process lock

fix: processLock causes high CPU usage

---

rpc/api/ledger_test.go
rpc/api/nep5_pledge.go
rpc/api/rewards.go
vm/contract/abi/abi_nep5_pledge.go
vm/contract/abi/abi_nep5_pledge_test.go
vm/contract/abi/abi_rewards.go
vm/contract/abi/abi_rewards_test.go
vm/contract/contract.go
vm/contract/nep5_pledge.go
vm/contract/nep5_pledge_test.go
vm/contract/rewards.go
vm/contract/rewards_test.go

- add test cases of staking contract
- add test cases of rewards contract
- fix #958 

test: add test cases of staking/rewards contract

---

.codecov.yml
common/types/block_contract_test.go
config/genesis_test.go
config/migration_v5_v6_test.go
rpc/api/ledger_mock_test.go
rpc/api/ledger_test.go
rpc/api/settlement_test.go
vm/contract/abi/abi_blackhole_test.go
vm/contract/abi/mock_block_mainnet_test.go
vm/contract/abi/mock_block_testnet_test.go
vm/contract/abi/mock_ledger_test.go
vm/contract/mock_ledger_test.go

test: fix testnet test cases

---

config/genesis_testnet_test.go
config/migration_v5_v6_testnet_test.go
rpc/api/settlement.go
vm/contract/abi/abi_settlement.go
vm/contract/abi/abi_settlement_test.go

-  virtual-router obtains the contract address by querying this interface, and then check whether the SMS has been processed according to the contract address + cdr data.
- fix #962 

feat: add get settlement contract address by partyAddress and stopName interface

---

rpc/api/ledger_test.go
rpc/api/mock_account_test.go
rpc/api/settlement.go
rpc/api/settlement_test.go
vm/contract/abi/abi_settlement.go

test: add settlement contract RPC test cases

---

vm/contract/abi/abi_settlement.go

fix: get settlement contract address bug

---

vm/contract/abi/abi_settlement.go
vm/contract/abi/abi_settlement_test.go

refactor: disable calculate service cost

---

consensus/pov/pov_chain_test.go
consensus/pov/pov_impl_test.go
consensus/pov/pov_pow_test.go
consensus/pov/pov_state.go
consensus/pov/pov_verifier_test.go
mock/mock.go
mock/mock_pov.go
mock/mock_pov_test.go
rpc/api/pov_test.go
rpc/api/public_key_distribution.go
rpc/api/public_key_distribution_test.go

add more pov testcase, such as rpc and consenses.

test: add more pov testcase

---

p2p/pinger/ping_test.go
rpc/api/net_test.go

test: add rpc testecase

---

ledger/db/badger_impl.go

- fix: value log truncate required to run db

fix: value log truncate required to run db

---

consensus/dpos/active_transaction_test.go
consensus/dpos/dpos_impl.go
consensus/dpos/dpos_impl_test.go
consensus/dpos/dpos_integration_test.go
consensus/dpos/dpos_test.go
consensus/dpos/online.go
consensus/dpos/processor.go
consensus/dpos/processor_test.go
vm/contract/mintage.go

fix: update dpos unit test

---

consensus/dpos/dpos_test.go
consensus/pov/pov_pow_test.go
ledger/cache_test.go
ledger/ledger_dump_test.go
ledger/ledger_pov_test.go
ledger/ledger_test.go
ledger/relation/relation_impl.go
ledger/relation/relation_manage.go
rpc/api/account_test.go
rpc/api/api_test.go
rpc/api/chain_test.go

- consensus testcase not close ledger normally, may cause UT fail
- add account api testcase

fix: ledger not closed normally in consensus testcase

---

common/goroutine.go
common/goroutine_test.go
config/verifier.go
config/verifier_test.go
consensus/dpos/active_transaction_test.go
consensus/dpos/dpos_impl_test.go
consensus/dpos/processor_test.go
rpc/api/settlement.go
rpc/api/settlement_test.go
vm/contract/abi/abi_settlement.go
vm/contract/abi/abi_settlement_enum.go
vm/contract/abi/abi_settlement_enum_test.go
vm/contract/abi/abi_settlement_gen.go
vm/contract/abi/abi_settlement_gen_test.go
vm/contract/abi/abi_settlement_test.go
vm/contract/contract.go
vm/contract/settlement.go
vm/contract/settlement_test.go

feat: implement asset registration

---

chain/miner_service.go
common/topic/messages.go
config/config_v4.go
config/migration_v5_v6.go
consensus/dpos/dpos_integration_test.go
consensus/pov/consensus_pov.go
consensus/pov/pov_chain.go
consensus/pov/pov_impl.go
consensus/pov/pov_impl_test.go
consensus/pov/pov_pow.go
consensus/pov/pov_pow_test.go
consensus/pov/pov_verifier_test.go
miner/cpu_mining.go
miner/miner.go
miner/miner_test.go
miner/pov_worker.go
mock/mock_pov.go
rpc/api/pov.go
rpc/api/pov_test.go

add pov builtin miner.
add pov params in config file.

feat: add pov builtin miner

---

mock/mock.go
rpc/api/mintage.go
rpc/api/mintage_test.go
rpc/api/nep5_pledge_test.go

test: add mintage and pledge testcase in rpc

---

ledger/cache.go
ledger/ledger_account.go
ledger/ledger_account_test.go
ledger/ledger_block.go
ledger/ledger_dump.go
ledger/ledger_frontier.go
ledger/ledger_generic.go
ledger/ledger_peersInfo.go
ledger/ledger_pending.go
ledger/ledger_represention.go
ledger/ledger_smartblock.go
ledger/ledger_sync.go
ledger/ledger_test.go
ledger/ledger_uncheck.go
ledger/ledger_vote_history.go
ledger/ledgerstore.go
ledger/process/cache_processor.go
ledger/process/cache_processor_test.go
ledger/process/ledger_check.go
ledger/process/ledger_processor.go
ledger/process/ledger_processor_test.go
ledger/process/rollback.go
ledger/process/rollback_test.go
mock/mocks/store.go
rpc/api/debug.go
rpc/api/debug_test.go
rpc/api/ledger_test.go

- add more ledger testcase
- add more rpc testcase
- format ledger code
- fix #960 

feat: add more ledger/rpc testcase

---

consensus/pov/pov_txpool_test.go
miner/miner_test.go

update pov cs and miner testcase.  

test: update pov cs and miner testcase

---

consensus/pov/common_test.go
consensus/pov/pov_chain_test.go
consensus/pov/pov_impl_test.go
consensus/pov/pov_verifier.go
consensus/pov/pov_verifier_test.go

test: add pov state testcase

---

chain/resendblock_service.go
chain/resendblock_service_test.go
common/topic/messages.go
ledger/process/cache_processor.go
p2p/node.go
p2p/qlcService.go
rpc/api/ledger.go

- fix get boot node error
- update resend service testcase
- put publish block in BlockCacheProcess function

feat: update getbootnode function and add some testcase

---

p2p/node.go

fix: get BootNode error

---

cmd/server/commands/root.go

- add dev mode,no pov ,no bootnode,easy debugging
- fix #1015 

feat: add dev mode

---

README.md
docker/Dockerfile
docker/Dockerfile_builder
docker/docker-compose.yml

**user and config directory changed from `/root` to `/qlcchain`**

feat: non-root user inside the Docker container

---

vm/contract/abi/abi_settlement.go
vm/contract/abi/abi_settlement_test.go

fix: multi-party/normal summary reports matching status

---

.github/workflows/go.yml
.github/workflows/release.yml
.github/workflows/reviewdog.yml

chore: update Github Actions

---

rpc/api/net.go
rpc/api/net_test.go

fix: method handler crashed when size<count

---

common/contract.go
common/topic/messages.go
common/vmcontract/contract.go
config/config_v2.go
config/config_v2_default.go
config/config_v2_testnet.go
consensus/dpos/dpos_impl.go
ledger/cache.go
p2p/node.go
p2p/protector.go
p2p/protector_test.go
p2p/qlcService.go
rpc/api/miner.go
rpc/api/miner_test.go
rpc/api/public_key_distribution.go
rpc/api/public_key_distribution_test.go
rpc/api/representative.go
rpc/api/representative_test.go
vm/contract/contract.go
vm/contract/permission.go
vm/contract/permission_test.go
vm/contract/settlement.go

feat: p2p module integrated permission mechanism

---

ledger/relation/relation_impl.go

-  reduplicate sqlite tx of sqlite

fix: reduplicate tx

---

consensus/dpos/dpos_test.go
consensus/dpos/processor.go
ledger/ledger_test.go
ledger/process/cache_processor.go
ledger/process/cache_processor_test.go
ledger/process/ledger_check.go
ledger/process/ledger_processor.go
ledger/process/ledger_processor_test.go
rpc/api/ledger.go

- block check indicate specific error message,fix #1042 

feat: block check indicate specific error message

---

chain/bootnode_http_service.go
chain/bootnode_http_service_test.go
config/config_v2.go
config/config_v2_default.go
config/config_v2_testnet.go
config/defaults_net.go
config/defaults_testnet.go
config/migration_v5_v6.go
p2p/discovery_test.go
p2p/messageMonitor_test.go
p2p/node.go
p2p/streamManager_test.go
p2p/sync_test.go

refactor: bootNode config

---

cmd/client/commands/debug.go
cmd/client/commands/debug_privacyinfo.go
common/event/feed_event_bus.go
consensus/dpos/dpos_impl.go
consensus/pov/pov_impl.go
ledger/process/ledger_processor.go
ledger/process/ledger_processor_test.go
miner/pov_worker.go
privacy/privacy.go
privacy/privacy_test.go
privacy/ptm.go
rpc/api/debug.go
rpc/api/ledger.go

- optimize privacy ptm client using pool #1065

feat: optimize privacy ptm client

---

cmd/client/commands/ptmkey.go
cmd/client/commands/ptmkey_getpubkey.go
cmd/client/commands/ptmkey_pkdelete.go
cmd/client/commands/ptmkey_pkupdate.go
cmd/client/commands/root.go
common/contract.go
common/contract_test.go
common/vmcontract/contractaddress/address.go
rpc/api/ptmkey.go
rpc/api/ptmkey_test.go
rpc/apis.go
vm/contract/abi/abi_ptmkey.go
vm/contract/abi/abi_ptmkey_test.go
vm/contract/ptmkey.go
vm/contract/ptmkey_test.go

* feat: resubmit ptmkey contract code(#1076)
* test: add ptmkey contract unit test cases
Signed-off-by: coolc4 <19464572@qq.com>

feat: Increase ptmkey contract unit test coverage(#1087)

---

vm/vmstore/vm_store.go
vm/vmstore/vm_store_test.go

test: add vm store test cases

---

ledger/ledger.go
ledger/ledger_relation_test.go

- relation register should be slice

feat: relation register should be slice

---

vm/contract/contract.go
vm/contract/ptmkey.go

The contract registration of the new structure has changed its position, this part of the registration code is not integrated
Signed-off-by: coolc4 <19464572@qq.com>

fix: ptmkey contract checkContractSendBlock failed

---

common/contract.go
common/contract_test.go
privacy/client.go
vm/contract/abi/abi_ptmkey.go
vm/contract/abi/abi_ptmkey_test.go
vm/contract/ptmkey.go
vm/contract/ptmkey_test.go

Signed-off-by: coolc4 <19464572@qq.com>

feat:add ptmkey new btypes {a2p,dod,cloud}

---

chain/permission_service.go
config/config_v6.go
config/config_v7.go
config/migration_v5_v6.go
config/migration_v6_v7.go
consensus/dpos/dpos_impl.go
consensus/dpos/processor.go
consensus/pov/pov_state.go
ledger/ledger_vm_store_test.go
ledger/relation/db/sqlite.go
rpc/api/ptmkey_test.go
vm/contract/abi/abi_ptmkey.go

fix: move privacy config to v7

---

rpc/api/dod_settlement.go
rpc/api/dod_settlement_test.go

- add some order query rpc interfaces for dod settlement

feat: add dod order rpc interfaces

---

rpc/api/dod_settlement.go
rpc/api/dod_settlement_test.go
vm/contract/abi/abi_dod_settlement.go
vm/contract/abi/abi_dod_settlement_test.go
vm/contract/abi/abi_dod_settlement_types.go
vm/contract/abi/abi_dod_settlement_types_gen.go
vm/contract/abi/abi_dod_settlement_types_test.go
vm/contract/dod_settlement.go
vm/contract/dod_settlement_test.go

- add more parameters check and logical check for dod-settlement smart contract

fix: add more dod settlement validation check

---

vm/vmstore/vm_store.go

new vmcontext can not get pov header by block height

fix: vmcontext can not get pov header by block height

---

vm/vmstore/vm_store.go

feat: adjust vm log print

---

rpc/api/dod_settlement.go
rpc/api/dod_settlement_test.go
vm/contract/abi/abi_dod_settlement_types.go

- add rpc getInternalIdByOrderId

feat: add rpc getInternalIdByOrderId

---

vm/contract/abi/abi_dod_settlement.go
vm/contract/abi/abi_dod_settlement_test.go
vm/contract/abi/abi_dod_settlement_types.go

- user can generate invoice with future time
- add flight/split to invoice response
- optimize code of generating invoice 

fix: optimize dod settlement invoice

---

chain/permission_service.go

- permission service auto add node issue

fix: permission service auto add node issue

---

common/storage/db/badger.go
common/storage/db/badger_test.go
common/storage/db/migration/migration.go
common/storage/db/migration/migration_test.go
go.mod
go.sum

feat: upgrade badger to v2.0

---

config/config_v2_default.go
config/config_v2_testnet.go
config/migration_v7_v8.go
rpc/api/debug.go
rpc/apis.go
rpc/rpc.go

feat: enable the RPC module according to the configuration file

---

.goreleaser.yml
Makefile
go.mod
go.sum

- bump go runtime to v1.14
- update build scripts
N/A

chore: update build scripts

---

cmd/client/commands/dod_settlement.go
cmd/client/commands/dod_settlement_change_order.go
cmd/client/commands/dod_settlement_change_response.go
cmd/client/commands/dod_settlement_create_order.go
cmd/client/commands/dod_settlement_create_response.go
cmd/client/commands/dod_settlement_terminate_order.go
cmd/client/commands/dod_settlement_terminate_response.go
cmd/client/commands/dod_settlement_update_order_info.go
cmd/client/commands/dod_settlement_update_product_info.go
cmd/client/commands/dod_settlement_update_response.go
cmd/client/commands/helper.go
cmd/client/commands/helper_testnet.go
cmd/client/commands/root.go
config/config_v8.go
config/migration_v7_v8.go
rpc/api/dod_settlement.go
rpc/api/dod_settlement_test.go
rpc/grpc/apis/dod_settlement.go
rpc/grpc/apis/dod_settlement_test.go
rpc/grpc/server/server.go

- move dod settlement contract to enterprise build

refactor: move dod settlement contract api to enterprise build

---

rpc/api/ledger_default_test.go
rpc/api/ledger_test.go
rpc/api/ledger_testnet_test.go

test: enable ledger test cases for both main net and test net

---

p2p/node.go

fix: peer statistics bug

---

consensus/dpos/dpos_impl.go
consensus/dpos/dpos_impl_testnet.go
ledger/ledger_block.go

- feat: call method to add confirmed block

refactor: call method to add confirmed block

---

ledger/ledger_pov.go
ledger/ledger_pov_test.go
mock/mocks/store.go
rpc/api/pov.go

- pov account tx num maybe incorrect 

fix: pov tx count

---

p2p/message_test.go
p2p/node_test.go

Signed-off-by: coolc4 <19464572@qq.com>
fix ：refactor p2p test cases issue（#1158）

test: refactor p2p test cases(#1158)

---

common/storage/db/migration/migration.go
common/storage/db/migration/migration_test.go
go.mod
go.sum

- upgrade badger db to v2.0 coexist with v1.6 library

feat: upgrade badger db to v2.0 coexist with v1.6 library

---

common/params_pov_testnet.go

feat: set testnet miner pledge to 0

---

rpc/api/debug.go

- feat: add BadgerTableSize debug

feat: add BadgerTableSize debug

---

.github/workflows/go.yml
cmd/client/commands/ledger.go
cmd/client/commands/ledger_init.go

- automatic assignment of Representatives
- QGAS allocation

feat: add client CLI to generate enterprise env

---

chain/ledger_service.go
config/config_v10.go
config/config_v10_testnet.go
go.mod
go.sum
rpc/api/debug.go
rpc/api/debug_test.go
rpc/api/net.go
rpc/api/pov.go

- feat: add node status debug interface

feat: add node status debug interface

---

ledger/ledger.go
ledger/ledger_privacy.go
ledger/ledger_privacy_test.go
ledger/ledger_test.go
mock/mocks/store.go
rpc/grpc/apis/ledger_test.go

feat: store privacy data with cache

---

chain/ledger_service.go
ledger/process/ledger_processor.go

fix: can not continue sync if interrupt

---

chain/context/chain_context.go
chain/context/chain_context_testnet.go
common/util/util.go
common/vmcontract/contractaddress/address.go
config/ConfigV11.go
config/defaults_net.go
config/defaults_testnet.go
config/migration_v10_v11.go
config/migration_v10_v11_test.go
mock/block.go
mock/bock_testnet.go
rpc/api/qgas_swap.go
rpc/api/qgas_swap_test.go
rpc/apis.go
rpc/apis_testnet.go
vm/contract/abi/abi_qgas_swap.go
vm/contract/abi/abi_qgas_swap_test.go
vm/contract/contract.go
vm/contract/contract_testnet.go
vm/contract/dod_settlement.go
vm/contract/qgas_swap.go
vm/contract/qgas_swap_test.go

- implement contract to pledge qgas, fix #1346

feat: implement contract to pledge qgas

---

config/config.go
config/config_test.go

feat: update config version

---

.github/CODEOWNERS
.github/workflows/go-qlc-builder.yml
.github/workflows/go.yml
.github/workflows/release.yml
chain/p2p_service_test.go
common/hashmap/hashmap_get.go
common/hashmap/util.go
ledger/cache_test.go
p2p/connectionGater_test.go
p2p/discovery_test.go
p2p/messageMonitor_test.go
p2p/node_test.go
p2p/streamManager_test.go
p2p/sync_test.go
rpc/api/ledger_test.go
rpc/grpc/apis/ledger_test.go
vm/contract/settlement_test.go

- update workflows
- fix go vet warning on golang v1.16.x

chore: update workflows and fix go vet warnings

---

vm/contract/qgas_swap.go

-  qgas pledge contract remove work checking

feat: qgas pledge contract remove work checking

---

.github/workflows/go.yml
rpc/api/pov.go
rpc/api/pov_test.go

- update pov api cache to optimize memory

feat: update pov api cache to optimize memory
